-- AlterTable
ALTER TABLE "pets" ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "age" DROP DEFAULT,
ALTER COLUMN "size" DROP DEFAULT,
ALTER COLUMN "energy_level" DROP DEFAULT,
ALTER COLUMN "environment_size" DROP DEFAULT,
ALTER COLUMN "independence_level" DROP DEFAULT;
